# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emploidutemps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conversation', models.CharField(choices=[('CONFLIT_EDT', 'Conflit EDT'), ('ABSENCE', 'Absence apprenant'), ('ANNONCE', 'Annonce admin'), ('GENERAL', 'Général')], default='GENERAL', max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_que_p1', to=settings.AUTH_USER_MODEL)),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_que_p2', to=settings.AUTH_USER_MODEL)),
                ('seance_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='emploidutemps.seance')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messagerie/fichiers/', verbose_name='Pièce jointe (max 10MB)')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['envoye_le'],
            },
        ),
    ]
