# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('centre', '0002_classe_alter_centre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total dû')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant versé')),
                ('reste_a_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reste à payer')),
                ('periode', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Période')),
                ('moyen', models.CharField(choices=[('MTN_MONEY', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Mobile Money'), ('VIREMENT', 'Virement bancaire')], default='MTN_MONEY', max_length=30, verbose_name='Moyen de paiement')),
                ('status', models.CharField(choices=[('COMPLET', 'Complet'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], default='PARTIEL', max_length=20)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise / Bourse')),
                ('est_bourse', models.BooleanField(default=False, verbose_name='Bourse')),
                ('date_paiement', models.DateField(auto_now_add=True, verbose_name='Date du paiement')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('mois_concerne', models.CharField(blank=True, max_length=20, verbose_name='Mois concerné')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='centre.anneeacademique')),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annules', to=settings.AUTH_USER_MODEL)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='apprenants.apprenant', verbose_name='Apprenant')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement scolaire',
                'verbose_name_plural': 'Paiements scolaires',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro de facture')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='Fichier PDF')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name="QR Code d'authenticité")),
                ('generee_le', models.DateTimeField(auto_now_add=True)),
                ('envoyee_par_email', models.BooleanField(default=False)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.paiementscolaire')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-generee_le'],
            },
        ),
    ]
