# Generated by Django 6.0.5 on 2026-05-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0002_inscription'),
        ('centre', '0003_periodemois_trimestre'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementscolaire',
            name='date_fin_couverture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de couverture'),
        ),
        migrations.AddField(
            model_name='paiementscolaire',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='apprenants.inscription', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='paiementscolaire',
            name='nombre_mois_couverts',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de mois couverts'),
        ),
        migrations.AlterField(
            model_name='paiementscolaire',
            name='mois_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='centre.periodemois', verbose_name='Mois concerné'),
        ),
        migrations.AlterField(
            model_name='paiementscolaire',
            name='status',
            field=models.CharField(choices=[('COMPLET', 'Complet'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé'), ('EN_ATTENTE', 'En attente')], default='PARTIEL', max_length=20),
        ),
    ]
