# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0002_classe_alter_centre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_parent', models.CharField(max_length=20, verbose_name='Téléphone parent')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('SORTI', 'Sorti')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Matricule')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('email_parent', models.EmailField(blank=True, max_length=254, verbose_name='Email parent')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='centre.classe', verbose_name='Classe / Niveau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenant_profil', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Apprenant',
                'verbose_name_plural': 'Apprenants',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
