# Generated by Django 6.0.5 on 2026-05-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0001_initial'),
        ('centre', '0003_periodemois_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('SORTI', 'Sorti'), ('TERMINE', 'Terminé')], default='ACTIF', max_length=20)),
                ('delai_admin_accorde_jusqua', models.DateField(blank=True, null=True)),
                ('suspendu_manuellement', models.BooleanField(default=False)),
                ('exonere', models.BooleanField(default=False)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='centre.anneeacademique')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apprenants.apprenant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='centre.classe')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('apprenant', 'annee_academique')},
            },
        ),
    ]
