# Generated by Django 6.0.5 on 2026-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0002_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_paiement_inscription',
            field=models.DateField(blank=True, null=True, verbose_name="Date de paiement des frais d'inscription"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='frais_inscription_paye',
            field=models.BooleanField(default=False, verbose_name="Frais d'inscription payés"),
        ),
    ]
