# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('emploidutemps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField(default=True, verbose_name='Présent')),
                ('motif_absence', models.TextField(blank=True, verbose_name="Motif d'absence")),
                ('enregistre_le', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('justifie_par', models.TextField(blank=True, verbose_name='Justification')),
                ('est_justifie', models.BooleanField(default=False, verbose_name='Absence justifiée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='apprenants.apprenant', verbose_name='Apprenant')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='emploidutemps.seance', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-enregistre_le'],
                'unique_together': {('seance', 'apprenant')},
            },
        ),
    ]
