# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('centre', '0002_classe_alter_centre_options_and_more'),
        ('enseignants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'évaluation")),
                ('type_eval', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('TP', 'Travaux Pratiques'), ('COMPOSITION', 'Composition'), ('INTERRO', 'Interrogation')], max_length=20, verbose_name='Type')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='Coefficient')),
                ('date_eval', models.DateField(verbose_name="Date de l'évaluation")),
                ('description', models.TextField(blank=True)),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_publiee', models.BooleanField(default=False, verbose_name='Notes publiées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='centre.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='enseignants.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='centre.matiere')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_eval'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('ANNUEL', 'Annuel')], max_length=20)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('effectif_classe', models.PositiveIntegerField(default=0)),
                ('appreciation', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='apprenants.apprenant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-genere_le'],
                'unique_together': {('apprenant', 'periode', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancienne note (traçabilité)')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='apprenants.apprenant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('apprenant', 'evaluation')},
            },
        ),
    ]
