# Generated by Django 6.0.5 on 2026-05-07 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du centre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centre/logos/', verbose_name='Logo (PNG/JPG/SVG, max 5MB)')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresse complète')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email du centre')),
                ('devise', models.CharField(choices=[('FCFA', 'FCFA — Franc CFA'), ('EUR', 'EUR — Euro'), ('USD', 'USD — Dollar')], default='FCFA', max_length=10, verbose_name='Devise')),
                ('annee_academique', models.CharField(default='2025–2026', max_length=20, verbose_name='Année scolaire en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_administres', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur principal')),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='centre.centre', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
                'unique_together': {('centre', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du niveau / groupe')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('frais_inscription', models.PositiveIntegerField(default=0, verbose_name="Frais d'inscription")),
                ('frais_mensuel', models.PositiveIntegerField(default=0, verbose_name='Frais mensuel')),
                ('frais_trimestriel', models.PositiveIntegerField(default=0, verbose_name='Frais trimestriel')),
                ('frais_annuel', models.PositiveIntegerField(default=0, verbose_name='Frais annuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='centre.centre', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['name'],
                'unique_together': {('centre', 'name')},
            },
        ),
    ]
