# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du niveau/groupe')),
                ('frais_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_trimestriel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe / Niveau',
                'verbose_name_plural': 'Classes / Niveaux',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name': 'Centre'},
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='updated_at',
            new_name='date_modification',
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='centre',
            name='admin',
        ),
        migrations.AddField(
            model_name='centre',
            name='configure_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_configures', to=settings.AUTH_USER_MODEL, verbose_name='Configuré par'),
        ),
        migrations.AddField(
            model_name='centre',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Année académique en cours'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='centre/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière'),
        ),
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Année en cours')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees_academiques', to='centre.centre')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='centre',
        ),
    ]
