# Generated by Django 6.0.5 on 2026-05-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_classe_alter_centre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mois', to='centre.anneeacademique')),
            ],
            options={
                'verbose_name': 'Mois',
                'verbose_name_plural': 'Mois',
                'ordering': ['numero'],
                'unique_together': {('annee', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='centre.anneeacademique')),
                ('mois', models.ManyToManyField(blank=True, related_name='trimestres', to='centre.periodemois')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['ordre'],
                'unique_together': {('annee', 'ordre')},
            },
        ),
    ]
