# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0002_classe_alter_centre_options_and_more'),
        ('enseignants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=20)),
                ('est_ferie', models.BooleanField(default=False, verbose_name='Férié')),
                ('est_vacance', models.BooleanField(default=False, verbose_name='Vacances')),
            ],
            options={
                'verbose_name': 'Journée',
                'verbose_name_plural': 'Journées',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee_scolaire', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='centre.anneeacademique')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(verbose_name='Date de la séance')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('PREVUE', 'Prévue'), ('REALISEE', 'Réalisée'), ('ANNULEE', 'Annulée')], default='PREVUE', max_length=20)),
                ('est_recurrent', models.BooleanField(default=False, verbose_name='Cours récurrent')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_annulees', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='centre.classe', verbose_name='Classe')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='emploidutemps.emploidutemps')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='enseignants.enseignant', verbose_name='Enseignant')),
                ('journee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='emploidutemps.journee')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='centre.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message du signalement')),
                ('resolu', models.BooleanField(default=False)),
                ('signale_le', models.DateTimeField(auto_now_add=True, verbose_name='Signalé le')),
                ('resolu_le', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('resolution_message', models.TextField(blank=True, verbose_name='Message de résolution')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='enseignants.enseignant', verbose_name='Enseignant signalant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par (admin)')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='emploidutemps.seance', verbose_name='Séance concernée')),
            ],
            options={
                'verbose_name': 'Requête / Conflit EDT',
                'verbose_name_plural': 'Requêtes / Conflits EDT',
                'ordering': ['-signale_le'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semaine', models.PositiveIntegerField(verbose_name='Numéro de semaine')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('jours_ouverts', models.CharField(default='Lundi,Mardi,Mercredi,Jeudi,Vendredi', max_length=100, verbose_name='Jours ouvrés')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='emploidutemps.emploidutemps')),
            ],
            options={
                'verbose_name': 'Semaine',
                'verbose_name_plural': 'Semaines',
                'ordering': ['date_debut'],
                'unique_together': {('emploi_du_temps', 'numero_semaine')},
            },
        ),
        migrations.AddField(
            model_name='journee',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journees', to='emploidutemps.semaine'),
        ),
        migrations.AlterUniqueTogether(
            name='journee',
            unique_together={('semaine', 'date')},
        ),
    ]
