# Generated by Django 6.0.5 on 2026-05-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_periodemois_trimestre'),
        ('emploidutemps', '0001_initial'),
        ('enseignants', '0002_alter_enseignant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la salle')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('capacite', models.PositiveIntegerField(default=30, verbose_name='Capacité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, verbose_name='Salle active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='emploidutemps.salle', verbose_name='Salle'),
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('jour', 'heure_debut', 'classe'), ('jour', 'heure_debut', 'enseignant'), ('jour', 'heure_debut', 'salle')},
        ),
    ]
