# Generated by Django 6.0.5 on 2026-05-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploidutemps', '0002_salle_seance_salle_alter_seance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidutemps',
            name='annee_scolaire',
        ),
    ]
