# Generated by Django 6.0.5 on 2026-05-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('PAIEMENT', 'Paiement enregistré'), ('SEANCE_ANNULEE', 'Séance annulée'), ('SEANCE_MODIFIEE', 'Séance modifiée'), ('BULLETIN', 'Bulletin disponible'), ('MESSAGE', 'Nouveau message'), ('RAPPEL_PAIEMENT', 'Rappel paiement'), ('CONFLIT_EDT', 'Conflit EDT signalé'), ('EDT_PUBLIE', 'EDT publié'), ('NOTE_SAISIE', 'Notes saisies'), ('ABSENCE', 'Absence signalée')], max_length=30)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('lue_le', models.DateTimeField(blank=True, null=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('lien_url', models.CharField(blank=True, max_length=300, verbose_name='Lien URL')),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet concerné')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-creee_le'],
            },
        ),
    ]
