# Generated by Django 6.0.5 on 2026-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_periodemois_trimestre'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='biographie',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='specialites',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='date_recrutement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de recrutement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='centre.matiere', verbose_name='Matières enseignées'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='centre.classe', verbose_name='Niveaux / groupes affectés'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spécialité / domaine'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('INCOMPLET', 'Profil incomplet'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='INCOMPLET', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
